version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: -e .
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest --version
          name: Print pytest version
  test:
    executor: python/default
    steps:
      - run:
          command: python -m pytest .
          name: Run unit tests

workflows:
  main:
    jobs:
      - build-and-test

